name: Backstop JS Visual Regression Test
on: [push]

jobs:
  Visual-Regression-Test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn
      - name: Run Visual Regression Test with BackstopJS
        run: yarn backstop:test
      - name: Upload reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: |
            backstop_output
            backstop_data/bitmaps_reference
          if-no-files-found: error
